// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2R11RJIMDJKLfbgRBW5C3VLGkOCaC2zk',
    appId: '1:580410564749:web:125e557c8776c1a2c382c4',
    messagingSenderId: '580410564749',
    projectId: 'deshv4',
    authDomain: 'deshv4.firebaseapp.com',
    storageBucket: 'deshv4.firebasestorage.app',
    measurementId: 'G-BR120WLDD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxhJdKm_bmfUCaK-1TfCafLcib-ZBKMRc',
    appId: '1:580410564749:android:ee4448ed708db84bc382c4',
    messagingSenderId: '580410564749',
    projectId: 'deshv4',
    storageBucket: 'deshv4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN4JM_3s_jw-i9Xt9h8dwqWtanQMp_EKw',
    appId: '1:580410564749:ios:92bbd71d6ea86d62c382c4',
    messagingSenderId: '580410564749',
    projectId: 'deshv4',
    storageBucket: 'deshv4.firebasestorage.app',
    iosBundleId: 'com.deshexplorer.deshexplorer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN4JM_3s_jw-i9Xt9h8dwqWtanQMp_EKw',
    appId: '1:580410564749:ios:92bbd71d6ea86d62c382c4',
    messagingSenderId: '580410564749',
    projectId: 'deshv4',
    storageBucket: 'deshv4.firebasestorage.app',
    iosBundleId: 'com.deshexplorer.deshexplorer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2R11RJIMDJKLfbgRBW5C3VLGkOCaC2zk',
    appId: '1:580410564749:web:792b337b9c74e498c382c4',
    messagingSenderId: '580410564749',
    projectId: 'deshv4',
    authDomain: 'deshv4.firebaseapp.com',
    storageBucket: 'deshv4.firebasestorage.app',
    measurementId: 'G-SSWS728QSY',
  );
}
