import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'config/app_config.dart';
import 'core/router/app_router.dart';
import 'core/theme/app_theme.dart';
import 'providers/theme_provider.dart';

// Firebase imports are gated behind AppConfig.useFirebase at runtime, but
// the import itself is safe to keep even before google-services.json is
// added — firebase_core simply won't be initialized.
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart'; // generated by `flutterfire configure`

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ---------------------------------------------------------------------
  // FIREBASE SETUP (currently disabled — see lib/config/app_config.dart)
  // ---------------------------------------------------------------------
  // Once you have added:
  //   - android/app/google-services.json
  //   - ios/Runner/GoogleService-Info.plist
  // run `flutterfire configure` to generate lib/firebase_options.dart, then:
  //
  // if (AppConfig.useFirebase) {
  //   await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // }
  //
  // and set AppConfig.useFirebase = true.
  // ---------------------------------------------------------------------

  runApp(const ProviderScope(child: DeshExplorerApp()));
}

class DeshExplorerApp extends ConsumerWidget {
  const DeshExplorerApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);
    final themeMode = ref.watch(themeModeProvider);

    return MaterialApp.router(
      title: 'DeshExplorer',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: themeMode,
      routerConfig: router,
    );
  }
}
